### ISSUE TITLE
Black failing due to missing Python import

### ISSUE THREAD

**Issue by tbpg** [googleapis/doc-templates#319]
See https://source.cloud.google.com/results/invocations/68c134d7-32d8-4e70-be8c-dd1b0ceb190b/targets.

```
Traceback (most recent call last):
  File "/h/.local/bin/black", line 5, in <module>
    from black import patched_main
  File "/h/.local/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
    from typed_ast import ast3, ast27
  File "/h/.local/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3
ImportError: /h/.local/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
```

Note this seems to come from running `black` (line 27):
https://github.com/googleapis/doc-templates/blob/99f91202a1b33479f01770b803e33e75edfac07d/ci/run_tests.sh#L24-L28

**Comment by tbpg** [comment]
Reproduced locally with:

```
docker pull gcr.io/cloud-devrel-kokoro-resources/docfx 
TRAMPOLINE_BUILD_FILE=./ci/run_tests.sh TRAMPOLINE_IMAGE=gcr.io/cloud-devrel-kokoro-resources/docfx ci/trampoline_v2.sh
```

Found https://github.com/python/typed_ast/issues/169, which indicates the problem should go away if we upgrade `black`.

**Comment by tbpg** [comment]
From the release notes, the dependency was removed in 21.4b0. See https://black.readthedocs.io/en/stable/change_log.html#id21.

I'll send a PR to upgrade.
